name: "Create a Release Tag"
description: "Create a Release Tag via CI/CD pipeline"
inputs:
  tag:
    description: "The name of the tag to create"
    required: true
  message:
    description: "The message associated with the tag"
    required: false
  tag_exists_error:
    description: "Whether to throw an error if the tag already exists"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - id: create-a-release-tag
      run: |        
        echo "Tag: ${{ inputs.tag }} "
        echo "Message: ${{ inputs.message }} "
        echo "Tag Exists Error: ${{ inputs.tag_exists_error }} "
      shell: bash

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: "0"

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: "5.x"

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7

    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Check if the tag already exists
      shell: bash
      run: |
        TAG_EXISTS=$(git ls-remote --tags origin | grep -c "refs/tags/${TAG}")
        if [ "$TAG_EXISTS" -ne 0 ]; then
          if [ "$TAG_EXISTS_ERROR" = "true" ]; then
            echo "Error: Tag ${TAG} already exists."
            exit 1
          else
            echo "Tag ${TAG} already exists. Skipping creation."
            exit 0
          fi
        fi

    - name: Create the New Tag
      shell: bash
      run: |
        git tag -a ${{ inputs.tag }} -m "${{ inputs.message }}"
        git push origin ${{ inputs.tag }}
        echo " ✅  New Release Generated Successfully  🎯 "        
        echo " ✨  New Release Tag (${{ inputs.tag }}) ✨ "
